# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce99f2246d5e776461cc54b29eb9d1e7f5d62865a1fc57b6ba2848567e8a452d422413c12a82a6b6d05fa504d82bf1450ae139e891734841b7b1d1132ecee705

test:
  secret_key_base: 276203e42220bb8e271010167a192646f7768124cd68adb3e198da8576239ba2fc56bc976e7dbab52065fadd9987ec00ed2b0e4e0093e8d2b85ec7ed723213c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
